### ISSUE TITLE
learning to do all this

### ISSUE THREAD

**Issue by SiobhanSheehan** [SiobhanSheehan/treehouse#2]

**Comment by SiobhanSheehan** [comment]
##todo

**Comment by SiobhanSheehan** [comment]
**Finishing the GITHUB course**
* [ ] figuring out all the coding 
* [ ] getting gitbash to work
* [ ] asking a lot of questions

👍 🎈
